### PR TITLE
scripts/legal_info_html.sh: close omitted div

### PR DESCRIPTION
**Pull request by commodo**
During change 36fbc8f0511e6db ("build: parametrize ADI legal info for
`Written Offer`"), an open <div> was left open.
Fixed this.
Validated with https://validator.w3.org/#validate_by_upload

Signed-off-by: Alexandru Ardelean <alexandru.ardelean@analog.com>

### CODE REVIEW

**Comment by rgetz** [comment]
Did you want to use $TARGET vs $ADI_LEGAL? 

I don't understand why we need to add a new variable people have to manage.

**Comment by commodo** [comment]
Well, we could use $TARGET now, and change later.
The intent was to make this a bit future-proof, where, if we add more [ADI] targets to this repo, we could avoid changing the `if [ $TARGET == Pluto ] || [ $TARGET == m2k ] || [ $TARGET == something_new ] ` and just have an `ADI_LEGAL` var in `<new_target>.mk` include.
But that all depends on future cases.

For now, I don't have any strong opinions on either matter.
So, whatever you prefer [using ADI_LEGAL var or TARGET var] is fine from me :)

**Comment by rgetz** [comment]
So, if the current plan is to have seperate repos for M2k and Pluto? (Like we have today?). Then I don't think this makes sense. Each repo will handle its boards, and derivatives. 

I think TARGET is OK, and simplifies things.

**Comment by commodo** [comment]
ack;
will add a new change to use the $TARGET var

**Comment by commodo** [comment]
Changelog v1 -> v2:
* remove `ADI_LEGAL` var ; use `TARGET` var instead

**Pull request merged**
